name: Check datafiles
author: BSData
description: >
  Compiles, checks and tests datafiles in the repository in terms
  of validity, integrity and bugs, saves generated artifacts to
  'staging-path' (output).
inputs:
  token:
    description: GitHub auth token to authorize uploading release assets
    required: false
    default: ${{ github.token }}
  staging-path:
    description: Path where generated assets will be saved (set as output as well).
    required: false
    default: ${{ runner.temp }}/assets
outputs:
  staging-path:
    description: Path where generated assets were saved.
    value: ${{ inputs.staging-path }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/action.ps1 -StagingPath $env:STAGING_PATH
      shell: pwsh
      id: script
      env:
        STAGING_PATH: ${{ inputs.staging-path }}
branding:
  icon: book-open
  color: blue
